#!/usr/bin/env python

def rule1(password):
	"""Passwords must include one increasing straight of at least three letters, like abc,
	 bcd, cde, and so on, up to xyz. They cannot skip letters; abd doesn't count."""
	for i in range(len(password) - 2):
		a, b, c = password[i:i+3]
		if ord(c) - ord(b) == 1 and ord(b) - ord(a) == 1:
			return True
	return False

def rule2(password):
	"""Passwords may not contain the letters i, o, or l, as these letters can be mistaken
	for other characters and are therefore confusing."""
	for c in password:
		if c in "iol":
			return False
	return True

def rule3(password):
	from itertools import groupby
	"""Passwords must contain at least two different, non-overlapping pairs of letters,
	like aa, bb, or zz."""
	groups = filter(lambda x: len(x) == 2, [list(g) for k, g in groupby(password)])
	if len(groups) == 2:
		a, b = groups
		return a != b
	return False

def increase_string(s):
	if s[-1] == 'z':
		return increase_string(s[:-1]) + 'a'
	else:
		return s[:-1] + chr(ord(s[-1]) + 1)

def is_valid_password(password):
	return rule1(password) and rule2(password) and rule3(password)

def next_password(password):
	while True:
		if is_valid_password(password):
			return password
		else:
			password = increase_string(password)

def main():
	password = next_password("vzbxkghb")
	print "Part 1: Santas next password should be \"%s\"" % password
	print "Part 2: Santas next password should be \"%s\"" % next_password(increase_string(password))
	return 0

if __name__ == "__main__":
	exit(main())
